<a href="https://colab.research.google.com/github/SP-TechForest/Python-creations/blob/main/ML__Association_Rule_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np 
import plotly.express as px 
import matplotlib.pyplot as plt

In [17]:
data = pd.read_csv("Market_Basket_Optimisation.csv", header= None)

In [18]:
data.shape

(7501, 20)

In [23]:
data.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
na_columns = data.columns[data.isna().any()]

In [13]:
data[na_columns].isna().mean().sort_values(ascending = False)

olive oil            1.000000
spinach              0.999733
frozen smoothie      0.999600
antioxydant juice    0.999600
salmon               0.999067
mineral water        0.996800
salad                0.993867
honey                0.988533
green tea            0.979600
low fat yogurt       0.966000
tomato juice         0.947467
energy drink         0.912933
cottage cheese       0.869333
yams                 0.817600
whole weat flour     0.751600
green grapes         0.662933
vegetables mix       0.554133
avocado              0.414933
almonds              0.233867
dtype: float64

In [15]:
data[na_columns].isna().mean().sort_values(ascending = False).axes[0][:18]

Index(['olive oil', 'spinach', 'frozen smoothie', 'antioxydant juice',
       'salmon', 'mineral water', 'salad', 'honey', 'green tea',
       'low fat yogurt', 'tomato juice', 'energy drink', 'cottage cheese',
       'yams', 'whole weat flour', 'green grapes', 'vegetables mix',
       'avocado'],
      dtype='object')

In [30]:
transaction = []
for i in range(data.shape[0]):
  transaction.append([str(data.values[i,j]) for j in range(data.shape[1])])

In [31]:
len(transaction)

7501

In [106]:
from apyori import apriori
rules = apriori(transactions= transaction, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

In [107]:
results = list(rules)

In [131]:
def inspect_rules(results):
  for i in range(len(results)):
    lhs = [tuple(result[2][0][0])[0] for result in results]
    rhs = [tuple(result[2][0][1])[0] for result in results]
    confi = [result[2][0][2] for result in results]
    sup = [result[1] for result in results]
    lift = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, confi, sup, lift))

In [132]:
report_rules = pd.DataFrame(inspect_rules(results), 
                            columns = ["Left_Hand_Side", "Right_Hand_Side", 
                                      "Confidence", "Support", "Lift"])

In [133]:
report_rules

         Left_Hand_Side Right_Hand_Side  Confidence   Support      Lift
0           light cream         chicken    0.290598  0.004533  4.843951
1  mushroom cream sauce        escalope    0.300699  0.005733  3.790833
2                 pasta        escalope    0.372881  0.005866  4.700812
3         fromage blanc           honey    0.245098  0.003333  5.164271
4         herb & pepper     ground beef    0.323450  0.015998  3.291994
5          tomato sauce     ground beef    0.377358  0.005333  3.840659
6           light cream       olive oil    0.205128  0.003200  3.114710
7     whole wheat pasta       olive oil    0.271493  0.007999  4.122410
8                 pasta          shrimp    0.322034  0.005066  4.506672

In [136]:
report_rules.nlargest(n = 10, columns = ["Lift"])

         Left_Hand_Side Right_Hand_Side  Confidence   Support      Lift
3         fromage blanc           honey    0.245098  0.003333  5.164271
0           light cream         chicken    0.290598  0.004533  4.843951
2                 pasta        escalope    0.372881  0.005866  4.700812
8                 pasta          shrimp    0.322034  0.005066  4.506672
7     whole wheat pasta       olive oil    0.271493  0.007999  4.122410
5          tomato sauce     ground beef    0.377358  0.005333  3.840659
1  mushroom cream sauce        escalope    0.300699  0.005733  3.790833
4         herb & pepper     ground beef    0.323450  0.015998  3.291994
6           light cream       olive oil    0.205128  0.003200  3.114710